Repository reactphp/http, pull requests merged in 2018-03, with the labels that each got.

#308 Do not pass $next handler to final request handler
  README.md
  src/Io/MiddlewareRunner.php
  tests/Io/MiddlewareRunnerTest.php
Labels: bug, easy pick

#301 Some code improvements
  examples/06-sleep.php
  src/Io/IniUtil.php
  src/Io/MiddlewareRunner.php
  src/Io/MultipartParser.php
  src/Io/PauseBufferStream.php
  src/Io/ServerRequest.php
  src/Middleware/LimitConcurrentRequestsMiddleware.php
  src/Server.php
  src/StreamingServer.php
Labels: easy pick, maintenance

#310 Documentation improvement
  README.md
Labels: easy pick, maintenance

#313 Fix awaiting queued handlers when cancelling a queued handler
  src/Middleware/LimitConcurrentRequestsMiddleware.php
  tests/Middleware/LimitConcurrentRequestsMiddlewareTest.php
Labels: bug
