Repository reactphp/http, pull requests merged in 2020-07, with the labels that each got.

#364 Run tests on PHPUnit 9 and clean up test suite
  .travis.yml
  composer.json
  phpunit.xml.dist
  tests/CallableStub.php
  tests/FunctionalServerTest.php
  tests/Io/ChunkedDecoderTest.php
  tests/Io/ChunkedEncoderTest.php
  tests/Io/EmptyBodyStreamTest.php
  tests/Io/HttpBodyStreamTest.php
  tests/Io/IniUtilTest.php
  tests/Io/LengthLimitedStreamTest.php
  tests/Io/MiddlewareRunnerTest.php
  tests/Io/RequestHeaderParserTest.php
  tests/Io/ServerRequestTest.php
  tests/Io/UploadedFileTest.php
  tests/Middleware/LimitConcurrentRequestsMiddlewareTest.php
  tests/Middleware/RequestBodyBufferMiddlewareTest.php
  tests/ServerTest.php
  tests/StreamingServerTest.php
  tests/TestCase.php
  tests/bootstrap.php
Labels: maintenance

#365 Fix calculating concurrency when `post_max_size` ini is unlimited
  src/Server.php
  tests/Io/IniUtilTest.php
  tests/ServerTest.php
Labels: bug

#367 Add `StreamingRequestMiddleware` to stream incoming requests, mark `StreamingServer` as internal
  README.md
  examples/08-stream-response.php
  examples/12-upload.php
  examples/13-stream-request.php
  examples/21-http-proxy.php
  examples/22-connect-proxy.php
  examples/31-upgrade-echo.php
  examples/32-upgrade-chat.php
  examples/99-benchmark-download.php
  src/Io/StreamingServer.php
  src/Middleware/LimitConcurrentRequestsMiddleware.php
  src/Middleware/StreamingRequestMiddleware.php
  src/Server.php
  tests/FunctionalServerTest.php
  tests/Io/StreamingServerTest.php
  tests/Middleware/StreamingRequestMiddlewareTest.php
  tests/ServerTest.php
Labels: BC break, new feature

#366 Add ReactPHP core team as authors to composer.json
  composer.json
Labels: maintenance

#368 Add HTTP client implementation (import clue/reactphp-buzz v2.9.0)
  LICENSE
  README.md
  composer.json
  examples/01-client-get-request.php
  examples/02-client-concurrent-requests.php
  examples/03-client-request-any.php
  examples/04-client-post-json.php
  examples/05-client-put-xml.php
  examples/11-client-http-connect-proxy.php
  examples/12-client-socks-proxy.php
  examples/13-client-ssh-proxy.php
  examples/14-client-unix-domain-sockets.php
  examples/21-client-request-streaming-to-stdout.php
  examples/22-client-stream-upload-from-stdin.php
  examples/51-server-hello-world.php
  examples/52-server-count-visitors.php
  examples/53-server-whatsmyip.php
  examples/54-server-query-parameter.php
  examples/55-server-cookie-handling.php
  examples/56-server-sleep.php
  examples/57-server-error-handling.php
  examples/58-server-stream-response.php
  examples/59-server-json-api.php
  examples/61-server-hello-world-https.php
  examples/62-server-form-upload.php
  examples/63-server-streaming-request.php
  examples/71-server-http-proxy.php
  examples/72-server-http-connect-proxy.php
  examples/81-server-upgrade-echo.php
  examples/82-server-upgrade-chat.php
  examples/91-client-benchmark-download.php
  examples/92-client-benchmark-upload.php
  examples/99-server-benchmark-download.php
  src/Browser.php
  src/Client/ChunkedStreamDecoder.php
  src/Client/Client.php
  src/Client/Request.php
  src/Client/RequestData.php
  src/Client/Response.php
  src/Io/ChunkedEncoder.php
  src/Io/Sender.php
  src/Io/Transaction.php
  src/Message/MessageFactory.php
  src/Message/ReadableBodyStream.php
  src/Message/ResponseException.php
  src/Server.php
  tests/BrowserTest.php
  tests/Client/DecodeChunkedStreamTest.php
  tests/Client/FunctionalIntegrationTest.php
  tests/Client/RequestDataTest.php
  tests/Client/RequestTest.php
  tests/Client/ResponseTest.php
  tests/FunctionalBrowserTest.php
  tests/Io/ChunkedEncoderTest.php
  tests/Io/SenderTest.php
  tests/Io/TransactionTest.php
  tests/Message/MessageFactoryTest.php
  tests/Message/ReadableBodyStreamTest.php
  tests/Message/ResponseExceptionTest.php
  tests/TestCase.php
Labels: new feature

#369 Add full core team to the license
  LICENSE
Labels: maintenance

#361 Add the event loop as required constructor argument
  README.md
  examples/51-server-hello-world.php
  examples/52-server-count-visitors.php
  examples/53-server-whatsmyip.php
  examples/54-server-query-parameter.php
  examples/55-server-cookie-handling.php
  examples/56-server-sleep.php
  examples/57-server-error-handling.php
  examples/58-server-stream-response.php
  examples/59-server-json-api.php
  examples/61-server-hello-world-https.php
  examples/62-server-form-upload.php
  examples/71-server-http-proxy.php
  examples/72-server-http-connect-proxy.php
  examples/81-server-upgrade-echo.php
  examples/82-server-upgrade-chat.php
  examples/99-server-benchmark-download.php
  src/Io/StreamingServer.php
  src/Server.php
  tests/FunctionalBrowserTest.php
  tests/FunctionalServerTest.php
  tests/Io/StreamingServerTest.php
  tests/ServerTest.php
Labels: BC break, maintenance, new feature

#362 Drop array as possible request handler
  README.md
  examples/62-server-form-upload.php
  src/Io/StreamingServer.php
  src/Server.php
  tests/FunctionalBrowserTest.php
  tests/FunctionalServerTest.php
  tests/Io/StreamingServerTest.php
  tests/ServerTest.php
Labels: BC break, maintenance

#370 Move `Response` class to `React\Http\Message\Response` and `ServerRequest` class to `React\Http\Message\ServerRequest`
  README.md
  examples/51-server-hello-world.php
  examples/52-server-count-visitors.php
  examples/53-server-whatsmyip.php
  examples/54-server-query-parameter.php
  examples/55-server-cookie-handling.php
  examples/56-server-sleep.php
  examples/57-server-error-handling.php
  examples/58-server-stream-response.php
  examples/59-server-json-api.php
  examples/61-server-hello-world-https.php
  examples/62-server-form-upload.php
  examples/63-server-streaming-request.php
  examples/71-server-http-proxy.php
  examples/72-server-http-connect-proxy.php
  examples/81-server-upgrade-echo.php
  examples/82-server-upgrade-chat.php
  examples/99-server-benchmark-download.php
  src/Io/RequestHeaderParser.php
  src/Io/StreamingServer.php
  src/Message/Response.php
  src/Message/ServerRequest.php
  src/Response.php
  src/Server.php
  tests/FunctionalBrowserTest.php
  tests/FunctionalServerTest.php
  tests/Io/MiddlewareRunnerTest.php
  tests/Io/MultipartParserTest.php
  tests/Io/StreamingServerTest.php
  tests/Message/ResponseTest.php
  tests/Message/ServerRequestTest.php
  tests/Middleware/LimitConcurrentRequestsMiddlewareTest.php
  tests/Middleware/RequestBodyBufferMiddlewareTest.php
  tests/Middleware/RequestBodyParserMiddlewareTest.php
  tests/Middleware/StreamingRequestMiddlewareTest.php
  tests/ResponseTest.php
  tests/benchmark-middleware-runner.php
Labels: BC break, new feature

#373 Tag Browser and mark public Message as final to discourage inheriting from it
  README.md
  src/Browser.php
  src/Message/Response.php
  src/Message/ResponseException.php
  src/Message/ServerRequest.php
Labels: maintenance

#371 Improve default concurrency and cap default request buffer at 64K
  README.md
  src/Io/StreamingServer.php
  src/Middleware/LimitConcurrentRequestsMiddleware.php
  src/Server.php
  tests/ServerTest.php
Labels: BC break, new feature

#372 Support skipping all online tests with `--exclude-group internet`
  README.md
  tests/Client/FunctionalIntegrationTest.php
  tests/FunctionalBrowserTest.php
  tests/Io/RequestHeaderParserTest.php
Labels: easy pick, maintenance

#374 Expose ReactPHP in `User-Agent` and `Server` header
  README.md
  src/Client/RequestData.php
  src/Io/StreamingServer.php
  tests/Client/RequestDataTest.php
  tests/Io/StreamingServerTest.php
Labels: easy pick, new feature

#375 Improve documentation and use fully-qualified class names throughout the documentation
  README.md
  src/Browser.php
  src/Io/MessageFactory.php
  src/Io/ReadableBodyStream.php
  src/Io/Sender.php
  src/Io/Transaction.php
  src/Message/Response.php
  src/Message/ResponseException.php
  src/Middleware/LimitConcurrentRequestsMiddleware.php
  src/Server.php
  tests/Io/MessageFactoryTest.php
  tests/Io/ReadableBodyStreamTest.php
  tests/Io/SenderTest.php
  tests/Io/TransactionTest.php
Labels: easy pick, maintenance

#379 Consistently resolve base URL according to HTTP specs
  README.md
  src/Browser.php
  src/Io/MessageFactory.php
  src/Io/Transaction.php
  tests/BrowserTest.php
  tests/Io/MessageFactoryTest.php
Labels: new feature

#380 Internal refactoring, remove unneeded MessageFactory helper class
  src/Browser.php
  src/Client/Response.php
  src/Io/MessageFactory.php
  src/Io/Sender.php
  src/Io/Transaction.php
  tests/FunctionalBrowserTest.php
  tests/Io/MessageFactoryTest.php
  tests/Io/SenderTest.php
  tests/Io/TransactionTest.php
Labels: maintenance

#381 Expose `Transfer-Encoding: chunked` response header and fix chunked responses for `HEAD` requests
  src/Client/ChunkedStreamDecoder.php
  src/Client/Response.php
  src/Io/ChunkedDecoder.php
  src/Io/Sender.php
  tests/Client/DecodeChunkedStreamTest.php
  tests/Client/ResponseTest.php
  tests/FunctionalBrowserTest.php
  tests/Io/ChunkedDecoderTest.php
Labels: bug, new feature
