Repository reactphp/http, pull requests merged in 2021-11, with the labels that each got.

#429 Explicitly close streaming response body when body MUST be empty
  src/Io/StreamingServer.php
  tests/Io/StreamingServerTest.php
Labels: bug, new feature

#430 Improve assigning `Content-Length` for `304 Not Modified` response
  src/Io/StreamingServer.php
  tests/Io/StreamingServerTest.php
Labels: bug, new feature

#431 Internal refactoring and improvement to hold message body in memory
  src/Io/BufferedBody.php
  src/Io/MultipartParser.php
  src/Io/Transaction.php
  src/Message/Response.php
  src/Message/ServerRequest.php
  tests/Io/UploadedFileTest.php
  tests/Message/ResponseTest.php
Labels: maintenance

#432 Expose all status code constants via `Response` class
  README.md
  composer.json
  examples/51-server-hello-world.php
  examples/52-server-count-visitors.php
  examples/53-server-whatsmyip.php
  examples/54-server-query-parameter.php
  examples/55-server-cookie-handling.php
  examples/56-server-sleep.php
  examples/57-server-error-handling.php
  examples/58-server-stream-response.php
  examples/59-server-json-api.php
  examples/61-server-hello-world-https.php
  examples/62-server-form-upload.php
  examples/63-server-streaming-request.php
  examples/71-server-http-proxy.php
  examples/72-server-http-connect-proxy.php
  examples/81-server-upgrade-echo.php
  examples/82-server-upgrade-chat.php
  examples/99-server-benchmark-download.php
  src/HttpServer.php
  src/Io/RequestHeaderParser.php
  src/Io/Sender.php
  src/Io/StreamingServer.php
  src/Message/Response.php
Labels: new feature

#433 Support PHP 8.1
  .github/workflows/ci.yml
Labels: new feature, easy pick
