Repository reactphp/http, pull requests merged in 2021-08, with the labels that each got.

#419 Simplify usage by supporting new Socket API without nullable loop arguments
  README.md
  composer.json
  examples/11-client-http-connect-proxy.php
  examples/12-client-socks-proxy.php
  examples/13-client-ssh-proxy.php
  examples/51-server-hello-world.php
  examples/52-server-count-visitors.php
  examples/53-server-whatsmyip.php
  examples/54-server-query-parameter.php
  examples/55-server-cookie-handling.php
  examples/56-server-sleep.php
  examples/57-server-error-handling.php
  examples/58-server-stream-response.php
  examples/59-server-json-api.php
  examples/61-server-hello-world-https.php
  examples/62-server-form-upload.php
  examples/63-server-streaming-request.php
  examples/71-server-http-proxy.php
  examples/72-server-http-connect-proxy.php
  examples/81-server-upgrade-echo.php
  examples/82-server-upgrade-chat.php
  examples/99-server-benchmark-download.php
  src/Browser.php
  src/Client/Client.php
  src/HttpServer.php
  src/Io/Sender.php
  src/Io/StreamingServer.php
  tests/Client/FunctionalIntegrationTest.php
  tests/FunctionalBrowserTest.php
  tests/FunctionalHttpServerTest.php
Labels: maintenance, new feature

#420 Update proxy examples to use simplified APIs thanks to default loop
  README.md
  composer.json
  examples/11-client-http-proxy.php
  examples/12-client-socks-proxy.php
  examples/13-client-ssh-proxy.php
Labels: new feature

#422 Don't run requests through configuration middleware
  src/HttpServer.php
  tests/HttpServerTest.php
Labels: new feature

#424 Fix documentation for missing `$body` argument for `put()` and `delete()` methods
  README.md
  src/Browser.php
Labels: bug, maintenance, easy pick
