Repository reactphp/http, pull requests merged in 2023-01, with the labels that each got.

#484 Consistently close HTTP client connections when response stream closes
  src/Io/ClientRequestStream.php
  src/Io/Sender.php
  tests/Io/ClientRequestStreamTest.php
  tests/Io/SenderTest.php
  tests/TestCase.php
Labels: bug, HTTP/1.1, HTTP/1.0

#486 Support HTTP keep-alive for HTTP client (reusing persistent connections)
  src/Browser.php
  src/Client/Client.php
  src/Io/ClientConnectionManager.php
  src/Io/ClientRequestStream.php
  src/Io/Sender.php
  src/Io/Transaction.php
  tests/BrowserTest.php
  tests/Client/FunctionalIntegrationTest.php
  tests/FunctionalBrowserTest.php
  tests/Io/ClientConnectionManagerTest.php
  tests/Io/ClientRequestStreamTest.php
  tests/Io/SenderTest.php
Labels: new feature, HTTP/1.1, HTTP/1.0

#487 Template params can only have one argument
  src/Browser.php
Labels: maintenance
